name: afrijourney
description: "Discover the Beauty of Zambia - Your Ultimate Tourism Guide"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  
  # State Management
  provider: ^6.1.1
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation and Routing
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  
  # Maps
  yandex_maps_mapkit_lite: ^4.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  image_picker: ^1.0.5
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  
  # Animations
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  
  # Logging and Debugging
  logger: ^2.0.2+1
  
  # Date and Time
  table_calendar: ^3.0.9
  
  # Notifications
  flutter_local_notifications: ^17.2.3 
  
  # Validation
  email_validator: ^2.1.17
  
  # Booking and Payments (if needed)
  # webview_flutter: ^4.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    # - assets/images/
    # - assets/icons/
    # - assets/animations/
    
    # Placeholder images for development
    # - assets/images/placeholder_image.png
    # - assets/images/no_image_available.png
    # - assets/images/default_profile.png
    # - assets/images/logo.png
    
    # Tourist attractions images
    - assets/victoria_falls.jpg
    - assets/south_luangwa.jpg
    - assets/kafue_park.jpg
    - assets/lower_zambezi.jpg
    - assets/kariba.jpg
    - assets/kasanka.jpg
    - assets/blue_lagoon.jpg
    - assets/livingstone_museum.jpg
    - assets/devils_pool.jpg
    - assets/zambezi_bridge.jpg
    
    # Accommodation images
    - assets/royal_livingstone.jpg
    - assets/tongabezi.jpg
    - assets/mfuwe_lodge.jpg
    - assets/avani_resort.jpg
    - assets/mukambi_lodge.jpg
    - assets/pioneer_camp.jpg
    
    # Cultural events images
    - assets/kuomboka.jpg
    - assets/ncwala.jpg
    - assets/lwiindi.jpg
    
    # Activities images
    - assets/bungee_jumping.jpg
    - assets/zip_lining.jpg
    - assets/safari_drive.jpg
    - assets/rafting.jpg
    - assets/helicopter_tour.jpg
    - assets/boat_cruise.jpg
    
  # Fonts (optional - Flutter uses default fonts if not specified)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700