name: afrijourney
description: "A comprehensive Zambia tourism app with backend integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.5
  
  # Location Services
  permission_handler: ^11.4.0
  geolocator: ^14.0.0
  
  # Internationalization
  intl: ^0.18.1
  
  # URL and External Links
  url_launcher: ^6.3.1
  
  # Logging
  logger: ^2.5.0
  
  # Maps
  yandex_maps_mapkit_lite: ^4.11.0-beta
  
  # HTTP Requests
  http: ^1.2.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # State Management
  provider: ^6.1.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Image Handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Date and Time
  table_calendar: ^3.0.9
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Device Info
  device_info_plus: ^9.1.1
  
  # Package Info
  package_info_plus: ^4.2.0
  
  # Animations
  lottie: ^2.7.0
  
  # File Operations
  path_provider: ^2.1.1
  
  # Database (if needed for offline storage)
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    # Existing assets
    - assets/zambia_hero.jpg
    - assets/victoria_falls.jpg
    - assets/south_luangwa.jpg
    - assets/lower_zambezi.jpg
    - assets/royal_livingstone.jpg
    - assets/tongabezi.jpg
    - assets/mfuwe_lodge.jpg
    - assets/mukambi_lodge.jpg
    - assets/pioneer_camp.jpg
    - assets/avani_resort.jpg
    - assets/kafue_park.jpg
    - assets/livingstone_museum.jpg
    - assets/kuomboka.jpg
    - assets/ncwala.jpg
    - assets/mutomboko.jpg
    - assets/shimunenga.jpg
    - assets/protea_hotel.jpg
    - assets/chaminuka_lodge.jpg
    - assets/bungee_jumping.jpg
    - assets/zip_lining.jpg
    - assets/safari_drive.jpg
    - assets/rafting.jpg

    # Additional assets for placeholders
    # - assets/placeholder_image.png
    # - assets/no_image_available.png
    # - assets/logo.png

    # Animation assets
    # - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700